export enum Errors {
  UNIQUE_KEY_VIOLATION = "UNIQUE_KEY_VIOLATION",
  UNSUPPORTED_GAME_SIZE = "UNSUPPORTED_GAME_SIZE",
  ERROR_UPLOADING_REC = "ERROR_UPLOADING_REC",
  ERROR_DOWNLOADING_REC = "ERROR_DOWNLOADING_REC",
  ERROR_FETCHING_RECS = "ERROR_FETCHING_RECS",
  ERROR_INCREMENTING_DOWNLOAD_COUNT = "ERROR_INCREMENTING_DOWNLOAD_COUNT",
}