import mongoose from "mongoose";
import PlayerDataSchema from "./PlayerData";

const Schema = mongoose.Schema;

const RecordedGameSchema = new Schema(
  {
    gameguid: { type: String, required: true },
    gamesessionguid: { type: String, required: true },
    playerdata: { type: [PlayerDataSchema], required: true },
    gamename: { type: String, default: "" },
    gametype: { type: Number, default: 0 },
    gamerestored: { type: Boolean, default: false },
    gamecurplayers: { type: Number, required: true },
    gamenumplayers: { type: Number, required: true },
    gamefreeforall: { type: Boolean, default: false },
    gamenomadstart: { type: Boolean, default: false },
    gamemapsize: { type: Number, default: 0 },
    gamemapname: { type: String, required: true },
    gamemaptype: { type: Number, default: 0 },
    gamefilename: { type: String, required: true },
    gamefilenameext: { type: String, required: true },
    gamefilecrc: { type: Number, required: true },
    gamerestrictpause: { type: Boolean, default: false },
    gamelastmapsetselected: { type: String, default: "" },
    gamemapresources: { type: Number, default: 0 },
    gameteamshareres: { type: Boolean, default: false },
    gameteamsharepop: { type: Boolean, default: false },
    gameteamlock: { type: Boolean, default: true },
    gameteambalanced: { type: Boolean, default: false },
    gamerandomseed: { type: Number, required: true },
    gamermdebug: { type: Boolean, default: false },
    gamedifficulty: { type: Number, required: true },
    gamerecordgame: { type: Boolean, default: false },
    gamestartingage: { type: Number, default: 0 },
    gameendingage: { type: Number, default: 4 },
    gamespeed: { type: Number, required: true },
    gamemapvisibility: { type: Number, default: 0 },
    gamemodetype: { type: Number, default: 0 },
    gamehandicapmode: { type: Number, default: 0 },
    gameallowcheats: { type: Boolean, default: false },
    gamehosttime: { type: Number, default: 0 },
    gamepassword: { type: String, default: "" },
    gamelatency: { type: Number, default: 0 },
    custommapname: { type: String, default: "" },
    gamenorush: { type: Number, default: 0 },
    gameblockade: { type: Boolean, default: false },
    gamekoth: { type: Boolean, default: false },
    gameregicide: { type: Boolean, default: false },
    gamesuddendeath: { type: Boolean, default: false },
    gameismpscenario: { type: Boolean, default: false },
    gameismpcoop: { type: Boolean, default: false },
    gamearenaseason: { type: String, default: "" },
    gamearenamission: { type: String, default: "" },
    gamearenaplayerchosendifficulty: { type: Number, default: 0 },
    gameconquest: { type: Boolean, default: false },
    gameaivsai: { type: Boolean, default: false },
    gamecampaignselected: { type: Number, default: 0 },
    gamecampaignprogress: { type: Number, default: 0 },
    gamecampaignfarthest: { type: Number, default: 0 },
    gamecampaignprogress1: { type: Number, default: 0 },
    gamecampaignfarthest1: { type: Number, default: 0 },
    gamecampaignprogress2: { type: Number, default: 0 },
    gamecampaignfarthest2act1: { type: Number, default: 0 },
    gamecampaignfarthest2act2: { type: Number, default: 0 },
    gamecampaignfarthest2act3: { type: Number, default: 0 },
    gamecontinuemainfilename: { type: String, default: "" },
    gamecontinuecampaignfilename: { type: String, default: "" },
    gamecontinuecampaignscenarioname: { type: String, default: "" },
    gamecontinuecampaignscenarionameid: { type: Number, default: 0 },
    gamecontinuecampaignid: { type: Number, default: 0 },
    gamecontinuecampaignscenarioid: { type: Number, default: 0 },
    gameregion: { type: String, default: "" },
    gamelanguage: { type: String, default: "" },
    gamecustommapfilecount: { type: Number, default: 0 },
    gamestartingresources: { type: Number, default: 0 },
    mapsetfilter: { type: Number, default: 0 },
    mapmodid: { type: Number, default: 0 },
    mapmodcrc: { type: Number, default: 0 },
    gamempcoopcampaignid: { type: Number, default: 0 },
    gamempcoopscenarioid: { type: Number, default: 0 },
    gameteamvictory: { type: Boolean, default: false },
    gameonevsall: { type: Boolean, default: false },
    gamemaprecommendedsettings: { type: Boolean, default: false },
    usedenforcedagesettings: { type: Boolean, default: false },
    gamemainmenuscenarioname: { type: String, default: "" },
    gameallowtitans: { type: Boolean, default: true },
    gamestorymode: { type: Boolean, default: false },
    gameallowaiassist: { type: Boolean, default: false },
    gamemilitaryautoqueue: { type: Boolean, default: false },
    gameplayfabpartyaddress: { type: String, default: "" }
  },
  { timestamps: true }
);

// define indexes
RecordedGameSchema.index({ gameguid: 1 }, { unique: true });

export default RecordedGameSchema;
